# Generated by Django 5.1.3 on 2024-12-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparsion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='predefinedfile',
            name='file',
            field=models.FileField(upload_to='predefined_files'),
        ),
    ]
